INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_AD9361 "libad9361")

FIND_PATH(AD9361_INCLUDE_DIRS
    NAMES ad9361.h
    HINTS ${PC_AD9361_INCLUDE_DIR}
    ${CMAKE_INSTALL_PREFIX}/include
    PATHS
    /usr/local/include
    /usr/include
)

FIND_LIBRARY(AD9361_LIBRARIES
    NAMES ad9361 libad9361
    HINTS ${PC_AD9361_LIBDIR}
    ${CMAKE_INSTALL_PREFIX}/lib
    ${CMAKE_INSTALL_PREFIX}/lib64
    PATHS
    ${AD9361_INCLUDE_DIRS}/../lib
    /usr/local/lib
    /usr/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(AD9361 DEFAULT_MSG AD9361_LIBRARIES AD9361_INCLUDE_DIRS)
MARK_AS_ADVANCED(AD9361_LIBRARIES AD9361_INCLUDE_DIRS)
